import type { CardTextDeck } from '../types.ts'

/**
 * English deck. Same ids and packs as pt-BR; idioms are adapted, not
 * translated word for word.
 */
export const enCards: CardTextDeck = {
    classic: [
        [1, 'Underrated', 'Overrated'],
        [2, 'Bad movie', 'Good movie'],
        [3, 'Bad song', 'Good song'],
        [4, 'Bad TV show', 'Good TV show'],
        [5, 'Boring book', 'Great book'],
        [6, 'Tacky', 'Classy'],
        [7, 'Cheesy', 'Stylish'],
        [8, 'Outdated', 'Trendy'],
        [9, 'Nerdy', 'Cool'],
        [10, 'Timeless classic', 'Passing fad'],
        [11, 'Forgettable', 'Unforgettable'],
        [12, 'Art', 'Not art'],
        [13, 'Sport', 'Not a sport'],
        [14, 'Hobby', 'Profession'],
        [15, 'Natural talent', 'Learned skill'],
        [16, 'Guilty pleasure', 'Proud to like it'],
        [17, 'Bad joke', 'Good joke'],
        [18, 'Not funny', 'Hilarious'],
        [19, 'Cringe', 'Cool'],
        [20, 'Villain', 'Hero'],
        [21, 'Annoying character', 'Beloved character'],
        [22, 'Badly acted', 'Well acted'],
        [23, 'Bad ending', 'Good ending'],
        [24, 'Predictable', 'Surprising'],
        [25, 'Bad food', 'Good food'],
        [26, 'Tastes bad', 'Tastes good'],
        [27, 'Smells bad', 'Smells good'],
        [28, 'Low calorie', 'High calorie'],
        [29, 'Zero nutrition', 'Superfood'],
        [30, 'Breakfast', 'Dinner'],
        [31, 'Snack', 'Meal'],
        [32, 'Sweet', 'Savory'],
        [33, 'Bland', 'Heavily seasoned'],
        [34, 'Kids’ food', 'Grown-up food'],
        [35, 'Eaten with your hands', 'Eaten with a knife and fork'],
        [36, 'Goes with ketchup', 'Never with ketchup'],
        [37, 'Dessert', 'Main course'],
        [38, 'Summer drink', 'Winter drink'],
        [39, 'Home cooking', 'Restaurant food'],
        [40, 'Bad fruit', 'Good fruit'],
        [41, 'Acceptable pizza', 'Unacceptable pizza'],
        [42, 'Useless', 'Essential'],
        [43, 'Cheap', 'Expensive'],
        [44, 'Fragile', 'Sturdy'],
        [45, 'Disposable', 'Lasts a lifetime'],
        [46, 'Easy to find', 'Hard to find'],
        [47, 'Common', 'Rare'],
        [48, 'Old', 'New'],
        [49, 'Ancient', 'Modern'],
        [50, 'Small', 'Big'],
        [51, 'Light', 'Heavy'],
        [52, 'Soft', 'Hard'],
        [53, 'Round', 'Pointy'],
        [54, 'Smooth', 'Rough'],
        [55, 'Dry', 'Wet'],
        [56, 'Hot', 'Cold'],
        [57, 'Quiet', 'Loud'],
        [58, 'Ugly', 'Beautiful'],
        [59, 'Fits in your pocket', 'Needs a truck'],
        [60, 'Useless tech', 'Revolutionary tech'],
        [61, 'Toy', 'Tool'],
        [62, 'Decorative', 'Practical'],
        [63, 'Bad gift', 'Great gift'],
        [64, 'Kid stuff', 'Grown-up stuff'],
        [65, 'Belongs at home', 'Belongs at the office'],
        [66, 'Introvert', 'Extrovert'],
        [67, 'Shy', 'Bold'],
        [68, 'Lazy', 'Hardworking'],
        [69, 'Too honest', 'Too polite'],
        [70, 'White lie', 'Serious lie'],
        [71, 'Bad habit', 'Good habit'],
        [72, 'Tolerable quirk', 'Unbearable quirk'],
        [73, 'Useless superpower', 'Amazing superpower'],
        [74, 'Boring job', 'Cool job'],
        [75, 'Dangerous job', 'Safe job'],
        [76, 'Underpaid', 'Well paid'],
        [77, 'Common name', 'Rare name'],
        [78, 'Dog name', 'Cat name'],
        [79, 'Lame excuse', 'Valid excuse'],
        [80, 'Optimist', 'Pessimist'],
        [81, 'Realist', 'Dreamer'],
        [82, 'Rude', 'Well-mannered'],
        [83, 'Old people thing', 'Young people thing'],
        [84, 'Pub talk', 'Work talk'],
        [85, 'Bad first date', 'Great first date'],
        [86, 'Red flag', 'Green flag'],
        [87, 'Easy task', 'Hard task'],
        [88, 'Boring to do', 'Fun to do'],
        [89, 'Relaxing', 'Stressful'],
        [90, 'Safe', 'Dangerous'],
        [91, 'Exhausting', 'Energizing'],
        [92, 'Done in a flash', 'Takes forever'],
        [93, 'Could do it in my sleep', 'Needs total focus'],
        [94, 'Daytime activity', 'Nighttime activity'],
        [95, 'Summer plan', 'Winter plan'],
        [96, 'Family outing', 'Night out with friends'],
        [97, 'Trip from hell', 'Dream trip'],
        [98, 'Nice place to visit', 'Nice place to live'],
        [99, 'Small town', 'Big city'],
        [100, 'Formal', 'Casual'],
        [101, 'Traditional', 'Innovative'],
        [102, 'Worth it', 'Not worth it'],
        [103, 'Waste of time', 'Time well spent'],
        [104, 'Bad luck', 'Good luck'],
        [105, 'Monday vibes', 'Saturday vibes'],
        [106, 'Solo activity', 'Group activity'],
        [107, 'Cute animal', 'Scary animal'],
        [108, 'Harmless animal', 'Dangerous animal'],
        [109, 'Dumb animal', 'Smart animal'],
        [110, 'Short-lived', 'Long-lived'],
        [111, 'Slow', 'Fast'],
        [112, 'Weak', 'Strong'],
        [113, 'Too small to see', 'Too big to imagine'],
        [114, 'Natural', 'Artificial'],
        [115, 'Clean', 'Dirty'],
        [116, 'Healthy', 'Bad for you'],
        [117, 'Science', 'Pseudoscience'],
        [118, 'Fact', 'Opinion'],
        [119, 'Early', 'Late'],
        [120, 'Past', 'Future'],
        [121, 'Small problem', 'Huge problem'],
        [122, 'Zero chance', 'Dead certain'],
        [123, 'Good', 'Evil'],
        [124, 'Simple', 'Complex'],
        [125, 'Normal', 'Weird'],
        [126, 'Easy', 'Difficult'],
        [127, 'Fun', 'Tedious'],
        [128, 'Famous', 'Unknown'],
        [129, 'Honest', 'Dishonest'],
        [130, 'Generous', 'Selfish'],
        [131, 'Brave', 'Cowardly'],
        [132, 'Important', 'Irrelevant'],
        [133, 'Just being fussy', 'Genuine need'],
        [134, 'Overhyped', 'Hidden gem'],
        [135, 'Childish', 'Mature'],
        [136, 'Romantic', 'Not romantic at all'],
        [137, 'Sin', 'Virtue'],
        [138, 'Chaotic', 'Organized'],
        [139, 'Silly fear', 'Justified fear'],
        [140, 'Good invention', 'Bad invention'],
        [141, 'Beginning of a story', 'End of a story'],
        [142, 'Everyone has it', 'Nobody has it'],
    ],

    food: [
        [1001, 'Dive bar food', 'Fine dining'],
        [1002, 'Weak coffee', 'Strong coffee'],
        [1003, 'Light bite', 'Food coma'],
        [1004, 'Weird combo', 'Perfect combo'],
        [1005, 'Ingredient that ruins it', 'Ingredient that saves it'],
        [1006, 'Kids’ party food', 'Wedding food'],
        [1007, 'Not spicy at all', 'Burns like fire'],
        [1008, 'Hospital food', 'Grandma’s cooking'],
        [1009, 'Easy to cook', 'Hard to cook'],
        [1010, 'Ready in 5 minutes', 'Takes all day'],
        [1011, 'Cheap at the store', 'Pricey at the store'],
        [1012, 'Acquired taste', 'Love at first bite'],
        [1013, '3 a.m. food', 'Sunday lunch'],
        [1014, 'Bad movie snack', 'Perfect movie snack'],
        [1015, 'Soggy', 'Crunchy'],
        [1016, 'No smell', 'Strong smell'],
        [1017, 'Actually healthy', 'Pretends to be healthy'],
        [1018, 'Gym food', 'Greasy food'],
        [1019, 'Weeknight dinner', 'Special occasion dish'],
        [1020, 'Made for sharing', 'Not sharing this'],
        [1021, 'I order it in', 'I make it myself'],
        [1022, 'Must-have seasoning', 'Optional seasoning'],
        [1023, 'Light dessert', 'Too rich to finish'],
        [1024, 'Quenches your thirst', 'Makes you thirstier'],
        [1025, 'Ugly food', 'Instagrammable food'],
        [1026, 'Picky eater food', 'For people who eat anything'],
        [1027, 'Airplane food', 'Chef’s tasting menu'],
        [1028, 'Fine cold', 'Only good hot'],
        [1029, 'Goes with rice', 'Never with rice'],
        [1030, 'Beach food', 'Cabin-in-the-woods food'],
        [1031, 'Clean to eat', 'Gets all over your face'],
        [1032, 'Way too sweet', 'Way too bitter'],
        [1033, 'Street food', 'White tablecloth'],
        [1034, 'Pantry staple', 'Gourmet ingredient'],
        [1035, 'Goes with everything', 'Goes with nothing'],
        [1036, 'Keeps for days', 'Goes bad the same day'],
        [1037, 'Underrated national dish', 'Overrated national dish'],
        [1038, 'Dish to impress guests', 'Dish to eat alone on the couch'],
        [1039, 'Party drink', 'Hangover drink'],
        [1040, 'Needs a recipe', 'I just eyeball it'],
        [1041, 'Taste of childhood', 'Flavor I just discovered'],
        [1042, 'College kitchen', 'MasterChef kitchen'],
        [1043, 'Everyday fruit', 'Exotic fruit'],
        [1044, 'Sad hotel breakfast', 'Dream hotel breakfast'],
    ],

    pop: [
        [2001, 'Lazy Sunday movie', 'Oscar movie'],
        [2002, 'Forgettable character', 'Iconic character'],
        [2003, 'Music to chill to', 'Music to jump to'],
        [2004, 'Easy karaoke song', 'Impossible karaoke song'],
        [2005, 'Pointless sequel', 'Sequel better than the original'],
        [2006, 'Mild spoiler', 'Unforgivable spoiler'],
        [2007, 'Trashy TV', 'Prestige TV'],
        [2008, 'Dead meme', 'Immortal meme'],
        [2009, 'Low-key celebrity', 'Tabloid celebrity'],
        [2010, 'Misunderstood villain', 'Unforgivable villain'],
        [2011, 'Relaxing game', 'Rage-inducing game'],
        [2012, 'Casual game', 'Hardcore game'],
        [2013, 'Binge-worthy show', 'One episode at a time'],
        [2014, 'Movie to watch alone', 'Movie to watch with family'],
        [2015, 'Actually scary horror', 'Laughably bad horror'],
        [2016, 'Forgettable soundtrack', 'Iconic soundtrack'],
        [2017, 'Well-deserved fame', 'Famous for no reason'],
        [2018, 'Cartoon for kids', 'Cartoon for adults'],
        [2019, 'Earworm', 'Song nobody remembers'],
        [2020, 'Summer hit', 'Timeless song'],
        [2021, 'Remake we needed', 'Remake nobody asked for'],
        [2022, 'Character I’d love to be', 'Character I’d hate to be'],
        [2023, 'Internet famous', 'Actually famous'],
        [2024, 'Movie too short', 'Movie too long'],
        [2025, 'Ending nobody understood', 'Obvious ending'],
        [2026, 'Predictable twist', 'Mind-blowing twist'],
        [2027, 'Easy Halloween costume', 'Hard Halloween costume'],
        [2028, 'Fine dubbed', 'Subtitles only'],
        [2029, 'Book was better', 'Movie was better'],
        [2030, 'Deep cut reference', 'Reference everyone gets'],
        [2031, 'Weak superhero', 'Overpowered superhero'],
        [2032, 'Fictional world I’d live in', 'Fictional world I’d run from'],
        [2033, 'Fictional couple that doesn’t work', 'Fictional couple goals'],
        [2034, 'Garage band', 'Stadium band'],
        [2035, 'Song to cry to', 'Song to dance to'],
        [2036, 'Forgettable music video', 'Legendary music video'],
        [2037, 'Boring board game', 'Addictive board game'],
        [2038, 'Fashion that should come back', 'Fashion that should stay dead'],
        [2039, 'Useless app', 'Can’t-live-without app'],
        [2040, 'Dumb trend', 'Genius trend'],
        [2041, 'Theme song I skip', 'Theme song I sing along to'],
        [2042, 'One-role actor', 'Chameleon actor'],
        [2043, 'Christmas movie', 'Not a Christmas movie'],
        [2044, 'Over-the-top action scene', 'Realistic action scene'],
    ],

    people: [
        [3001, 'Morning person', 'Night owl'],
        [3002, 'Replies instantly', 'Leaves you on read'],
        [3003, 'Always early', 'Always late'],
        [3004, 'Soft-spoken', 'Way too loud'],
        [3005, 'Plans everything', 'Wings it'],
        [3006, 'Holds a grudge', 'Forgives and forgets'],
        [3007, 'Big spender', 'Penny-pincher'],
        [3008, 'Quick voice note', 'Five-minute voice note'],
        [3009, 'Friend for a party', 'Friend for an emergency'],
        [3010, 'Harmless gossip', 'Dangerous gossip'],
        [3011, 'Sincere compliment', 'Backhanded compliment'],
        [3012, 'Normal question', 'Nosy question'],
        [3013, 'Golden advice', 'Terrible advice'],
        [3014, 'Retiree hobby', 'Teenager hobby'],
        [3015, 'Fond memory', 'Cringey memory'],
        [3016, 'Tiny slip-up', 'Legendary blunder'],
        [3017, 'Dream neighbor', 'Neighbor from hell'],
        [3018, 'Ideal coworker', 'Unbearable coworker'],
        [3019, 'Only I do this', 'Everyone does this'],
        [3020, 'Silly fight', 'Serious fight'],
        [3021, 'Terrible liar', 'Professional liar'],
        [3022, 'Not competitive at all', 'Way too competitive'],
        [3023, 'Apologizes for everything', 'Never apologizes'],
        [3024, 'Packs the night before', 'Packs a month ahead'],
        [3025, 'Fine on a first date', 'Not okay on a first date'],
        [3026, 'Easy to shop for', 'Impossible to shop for'],
        [3027, 'Stubborn', 'Goes with the flow'],
        [3028, 'Takes criticism well', 'Can’t take criticism'],
        [3029, 'Laughs at everything', 'Never laughs'],
        [3030, 'Fine at the movies', 'Banned at the movies'],
        [3031, 'Fine in public', 'Only at home alone'],
        [3032, 'Silly reason to break up', 'Serious reason to break up'],
        [3033, 'Childhood friend', 'Drinking buddy'],
        [3034, 'Dream boss', 'Nightmare boss'],
        [3035, 'Calm driver', 'Road rage'],
        [3036, 'Lives in the past', 'Lives in the future'],
        [3037, 'Justifiable splurge', 'Unjustifiable splurge'],
        [3038, 'Dog person', 'Cat person'],
        [3039, 'Backpacker', 'All-inclusive resort'],
        [3040, 'Zero patience', 'Endless patience'],
        [3041, 'Chats in the elevator', 'Stares at their phone'],
        [3042, 'Keeps secrets', 'Tells everyone everything'],
        [3043, 'Popular opinion', 'Hot take'],
        [3044, 'Too responsible', 'Irresponsible'],
    ],

    spicy: [
        [4001, 'Subtle flirting', 'Shameless flirting'],
        [4002, 'Awful first kiss', 'Movie-perfect first kiss'],
        [4003, 'Bad pickup line', 'Irresistible pickup line'],
        [4004, 'Tell my therapist', 'Take it to the grave'],
        [4005, 'Romantic gesture', 'Cringey gesture'],
        [4006, 'Not sexy at all', 'Very sexy'],
        [4007, 'Mild hangover', 'Hangover from another dimension'],
        [4008, 'Innocent late-night text', 'Dangerous late-night text'],
        [4009, 'Get back with your ex', 'Block your ex'],
        [4010, 'Vanilla fantasy', 'Wild fantasy'],
        [4011, 'Classic spot for a kiss', 'Unexpected spot for a kiss'],
        [4012, 'Could tell my mom', 'Never telling my mom'],
        [4013, 'Wholesome profile pic', 'Thirst trap'],
        [4014, 'Trustworthy dating profile', 'Sketchy dating profile'],
        [4015, 'Instant swipe right', 'Ruthless swipe left'],
        [4016, 'Drink to impress', 'Drink to forget'],
        [4017, 'Chill party', 'Legendary party'],
        [4018, 'Tiny sin', 'Deadly sin'],
        [4019, 'Summer fling', 'Love of a lifetime'],
        [4020, 'Cute jealousy', 'Toxic jealousy'],
        [4021, 'Boring gossip', 'Juicy gossip'],
        [4022, 'Friend’s secret', 'State secret'],
        [4023, 'First-date question', 'Tenth-date question'],
        [4024, 'Physical attraction', 'Intellectual attraction'],
        [4025, 'Natural charm', 'Rehearsed charm'],
        [4026, 'Forgivable drunk mistake', 'Unforgivable drunk mistake'],
        [4027, 'Okay for the family group chat', 'Never in the family group chat'],
        [4028, 'Low-key date outfit', 'Provocative date outfit'],
        [4029, 'Normal couple talk', 'Couple talk nobody wants to hear'],
        [4030, 'Slight turn-off', 'Total mood killer'],
        [4031, 'Acceptable dating app lie', 'Unforgivable dating app lie'],
        [4032, 'Night to remember', 'Night to forget'],
        [4033, 'Zero chemistry', 'Sparks flying'],
        [4034, 'Sweet confession', 'Cheesy confession'],
        [4035, 'Just a fling', 'Marriage material'],
        [4036, 'Tolerable bedtime habit', 'Dealbreaker bedtime habit'],
        [4037, 'Innocent', 'Naughty'],
        [4038, 'Subtle hint', 'Not-so-subtle hint'],
        [4039, 'Instant regret', 'Morning-after regret'],
        [4040, 'Worth the embarrassment', 'Not worth the embarrassment'],
        [4041, 'Tame bachelor party', 'Legendary bachelor party'],
        [4042, 'Saint', 'Sinner'],
        [4043, 'Movie kiss', 'Kiss from your aunt'],
        [4044, 'Innocent like', 'Like with ulterior motives'],
    ],
}
