import type { CardTextDeck } from '../types.ts'

/**
 * Mazo en español. Mismos ids y paquetes que pt-BR; las expresiones se
 * adaptan en lugar de traducirse palabra por palabra.
 */
export const esCards: CardTextDeck = {
    classic: [
        [1, 'Infravalorado', 'Sobrevalorado'],
        [2, 'Película mala', 'Película buena'],
        [3, 'Canción mala', 'Canción buena'],
        [4, 'Serie mala', 'Serie buena'],
        [5, 'Libro aburrido', 'Libro genial'],
        [6, 'Chabacano', 'Elegante'],
        [7, 'Cursi', 'Con estilo'],
        [8, 'Anticuado', 'De moda'],
        [9, 'Friki', 'Popular'],
        [10, 'Clásico', 'Moda pasajera'],
        [11, 'Olvidable', 'Inolvidable'],
        [12, 'Arte', 'No es arte'],
        [13, 'Deporte', 'No es deporte'],
        [14, 'Pasatiempo', 'Profesión'],
        [15, 'Talento natural', 'Habilidad entrenada'],
        [16, 'Placer culpable', 'Me gusta con orgullo'],
        [17, 'Chiste malo', 'Chiste bueno'],
        [18, 'Sin gracia', 'Graciosísimo'],
        [19, 'Vergüenza ajena', 'Lo más'],
        [20, 'Villano', 'Héroe'],
        [21, 'Personaje insoportable', 'Personaje adorado'],
        [22, 'Mal actuado', 'Bien actuado'],
        [23, 'Final malo', 'Final bueno'],
        [24, 'Predecible', 'Sorprendente'],
        [25, 'Comida mala', 'Comida buena'],
        [26, 'Sabe mal', 'Sabe bien'],
        [27, 'Huele mal', 'Huele bien'],
        [28, 'Pocas calorías', 'Muchas calorías'],
        [29, 'Nada nutritivo', 'Supernutritivo'],
        [30, 'Desayuno', 'Cena'],
        [31, 'Picoteo', 'Comida completa'],
        [32, 'Dulce', 'Salado'],
        [33, 'Soso', 'Muy condimentado'],
        [34, 'Comida de niños', 'Comida de adultos'],
        [35, 'Se come con la mano', 'Se come con cubiertos'],
        [36, 'Va con kétchup', 'Nunca con kétchup'],
        [37, 'Postre', 'Plato principal'],
        [38, 'Bebida de verano', 'Bebida de invierno'],
        [39, 'Comida casera', 'Comida de restaurante'],
        [40, 'Fruta mala', 'Fruta buena'],
        [41, 'Pizza aceptable', 'Pizza inaceptable'],
        [42, 'Inútil', 'Imprescindible'],
        [43, 'Barato', 'Caro'],
        [44, 'Frágil', 'Resistente'],
        [45, 'Desechable', 'Para toda la vida'],
        [46, 'Fácil de encontrar', 'Difícil de encontrar'],
        [47, 'Común', 'Raro'],
        [48, 'Viejo', 'Nuevo'],
        [49, 'Antiguo', 'Moderno'],
        [50, 'Pequeño', 'Grande'],
        [51, 'Ligero', 'Pesado'],
        [52, 'Blando', 'Duro'],
        [53, 'Redondo', 'Puntiagudo'],
        [54, 'Liso', 'Áspero'],
        [55, 'Seco', 'Mojado'],
        [56, 'Caliente', 'Frío'],
        [57, 'Silencioso', 'Ruidoso'],
        [58, 'Feo', 'Bonito'],
        [59, 'Cabe en el bolsillo', 'Necesita un camión'],
        [60, 'Tecnología inútil', 'Tecnología revolucionaria'],
        [61, 'Juguete', 'Herramienta'],
        [62, 'Decoración', 'Utilidad'],
        [63, 'Regalo malo', 'Regalo bueno'],
        [64, 'Cosa de niños', 'Cosa de adultos'],
        [65, 'Cosa de casa', 'Cosa de oficina'],
        [66, 'Introvertido', 'Extrovertido'],
        [67, 'Tímido', 'Atrevido'],
        [68, 'Vago', 'Trabajador'],
        [69, 'Demasiado sincero', 'Demasiado educado'],
        [70, 'Mentira piadosa', 'Mentira grave'],
        [71, 'Mal hábito', 'Buen hábito'],
        [72, 'Manía aceptable', 'Manía insoportable'],
        [73, 'Superpoder inútil', 'Superpoder increíble'],
        [74, 'Trabajo aburrido', 'Trabajo genial'],
        [75, 'Trabajo peligroso', 'Trabajo seguro'],
        [76, 'Mal pagado', 'Bien pagado'],
        [77, 'Nombre común', 'Nombre raro'],
        [78, 'Nombre de perro', 'Nombre de gato'],
        [79, 'Excusa barata', 'Excusa válida'],
        [80, 'Optimista', 'Pesimista'],
        [81, 'Realista', 'Soñador'],
        [82, 'Maleducado', 'Bien educado'],
        [83, 'Cosa de mayores', 'Cosa de jóvenes'],
        [84, 'Charla de bar', 'Charla de trabajo'],
        [85, 'Primera cita mala', 'Primera cita genial'],
        [86, 'Bandera roja', 'Bandera verde'],
        [87, 'Tarea fácil', 'Tarea difícil'],
        [88, 'Aburrido de hacer', 'Divertido de hacer'],
        [89, 'Relajante', 'Estresante'],
        [90, 'Seguro', 'Peligroso'],
        [91, 'Agotador', 'Revitalizante'],
        [92, 'Se hace en un momento', 'Lleva una eternidad'],
        [93, 'Lo hago dormido', 'Exige concentración total'],
        [94, 'Actividad de día', 'Actividad de noche'],
        [95, 'Plan de verano', 'Plan de invierno'],
        [96, 'Plan familiar', 'Plan con amigos'],
        [97, 'Viaje desastroso', 'Viaje soñado'],
        [98, 'Lugar para visitar', 'Lugar para vivir'],
        [99, 'Pueblo', 'Gran ciudad'],
        [100, 'Formal', 'Informal'],
        [101, 'Tradicional', 'Innovador'],
        [102, 'Vale la pena', 'No vale la pena'],
        [103, 'Pérdida de tiempo', 'Tiempo bien invertido'],
        [104, 'Da mala suerte', 'Da buena suerte'],
        [105, 'Cosa de lunes', 'Cosa de sábado'],
        [106, 'Para hacer solo', 'Para hacer en grupo'],
        [107, 'Animal tierno', 'Animal aterrador'],
        [108, 'Animal inofensivo', 'Animal peligroso'],
        [109, 'Animal tonto', 'Animal listo'],
        [110, 'Vive poco', 'Vive mucho'],
        [111, 'Lento', 'Rápido'],
        [112, 'Débil', 'Fuerte'],
        [113, 'Demasiado pequeño para verlo', 'Demasiado grande para imaginarlo'],
        [114, 'Natural', 'Artificial'],
        [115, 'Limpio', 'Sucio'],
        [116, 'Sano', 'Hace daño'],
        [117, 'Ciencia', 'Pseudociencia'],
        [118, 'Hecho', 'Opinión'],
        [119, 'Temprano', 'Tarde'],
        [120, 'Pasado', 'Futuro'],
        [121, 'Problema pequeño', 'Problema enorme'],
        [122, 'Probabilidad cero', 'Certeza absoluta'],
        [123, 'Bueno', 'Malo'],
        [124, 'Simple', 'Complejo'],
        [125, 'Normal', 'Raro'],
        [126, 'Fácil', 'Difícil'],
        [127, 'Divertido', 'Aburrido'],
        [128, 'Famoso', 'Desconocido'],
        [129, 'Honesto', 'Deshonesto'],
        [130, 'Generoso', 'Egoísta'],
        [131, 'Valiente', 'Cobarde'],
        [132, 'Importante', 'Irrelevante'],
        [133, 'Capricho', 'Necesidad'],
        [134, 'Puro hype', 'Joya escondida'],
        [135, 'Infantil', 'Maduro'],
        [136, 'Romántico', 'Nada romántico'],
        [137, 'Pecado', 'Virtud'],
        [138, 'Caótico', 'Ordenado'],
        [139, 'Miedo tonto', 'Miedo justificado'],
        [140, 'Buen invento', 'Mal invento'],
        [141, 'Principio de una historia', 'Final de una historia'],
        [142, 'Lo tiene todo el mundo', 'No lo tiene nadie'],
    ],

    food: [
        [1001, 'Comida de bar de barrio', 'Restaurante de lujo'],
        [1002, 'Café aguado', 'Café cargado'],
        [1003, 'Comida ligera', 'Comida que te deja KO'],
        [1004, 'Combinación rara', 'Combinación perfecta'],
        [1005, 'Ingrediente que lo arruina todo', 'Ingrediente que lo salva todo'],
        [1006, 'Comida de cumpleaños infantil', 'Comida de boda'],
        [1007, 'No pica nada', 'Pica muchísimo'],
        [1008, 'Comida de hospital', 'Comida de la abuela'],
        [1009, 'Fácil de cocinar', 'Difícil de cocinar'],
        [1010, 'Listo en 5 minutos', 'Lleva todo el día'],
        [1011, 'Barato en el súper', 'Caro en el súper'],
        [1012, 'Hay que acostumbrarse', 'Gusta al primer bocado'],
        [1013, 'Comida de madrugada', 'Comida de domingo'],
        [1014, 'Snack de cine malo', 'Snack de cine perfecto'],
        [1015, 'Blandito', 'Crujiente'],
        [1016, 'Sin olor', 'Olor fuerte'],
        [1017, 'Sano de verdad', 'Se hace pasar por sano'],
        [1018, 'Comida de gimnasio', 'Comida grasienta'],
        [1019, 'Plato de diario', 'Plato de ocasión especial'],
        [1020, 'Para compartir', 'No lo comparto con nadie'],
        [1021, 'Lo pido a domicilio', 'Lo hago en casa'],
        [1022, 'Condimento imprescindible', 'Condimento prescindible'],
        [1023, 'Postre ligero', 'Postre empalagoso'],
        [1024, 'Quita la sed', 'Da más sed'],
        [1025, 'Comida fea', 'Comida instagrameable'],
        [1026, 'Comida para niños quisquillosos', 'Para quien come de todo'],
        [1027, 'Comida de avión', 'Menú degustación'],
        [1028, 'Se puede comer frío', 'Solo vale caliente'],
        [1029, 'Va con arroz', 'Nunca con arroz'],
        [1030, 'Comida de playa', 'Comida de montaña'],
        [1031, 'Se come sin mancharse', 'Te pringas entero'],
        [1032, 'Demasiado dulce', 'Demasiado amargo'],
        [1033, 'Comida callejera', 'Mantel y vajilla fina'],
        [1034, 'Ingrediente básico', 'Ingrediente gourmet'],
        [1035, 'Combina con todo', 'No combina con nada'],
        [1036, 'Aguanta días en la nevera', 'Se estropea el mismo día'],
        [1037, 'Plato típico infravalorado', 'Plato típico sobrevalorado'],
        [1038, 'Plato para impresionar a las visitas', 'Plato para comer solo en el sofá'],
        [1039, 'Bebida de fiesta', 'Bebida de resaca'],
        [1040, 'Necesita receta', 'Lo hago a ojo'],
        [1041, 'Sabor de la infancia', 'Sabor que acabo de descubrir'],
        [1042, 'Cocina de estudiante', 'Cocina de MasterChef'],
        [1043, 'Fruta de mercado', 'Fruta exótica'],
        [1044, 'Desayuno de hotel triste', 'Desayuno de hotel soñado'],
    ],

    pop: [
        [2001, 'Peli de sobremesa', 'Peli de Óscar'],
        [2002, 'Personaje olvidable', 'Personaje icónico'],
        [2003, 'Música para relajarse', 'Música para saltar'],
        [2004, 'Karaoke fácil', 'Karaoke imposible'],
        [2005, 'Secuela innecesaria', 'Secuela mejor que la original'],
        [2006, 'Spoiler leve', 'Spoiler imperdonable'],
        [2007, 'Telebasura', 'Televisión de calidad'],
        [2008, 'Meme muerto', 'Meme eterno'],
        [2009, 'Famoso discreto', 'Famoso de escándalo'],
        [2010, 'Villano incomprendido', 'Villano sin perdón'],
        [2011, 'Juego para relajarse', 'Juego que da rabia'],
        [2012, 'Juego casual', 'Juego hardcore'],
        [2013, 'Serie para maratonear', 'Serie para ver con calma'],
        [2014, 'Peli para ver solo', 'Peli para ver en familia'],
        [2015, 'Terror que da miedo', 'Terror que da risa'],
        [2016, 'Banda sonora olvidable', 'Banda sonora icónica'],
        [2017, 'Fama merecida', 'Famoso sin explicación'],
        [2018, 'Dibujos para niños', 'Dibujos para adultos'],
        [2019, 'Canción pegadiza', 'Canción que nadie recuerda'],
        [2020, 'Canción del verano', 'Canción eterna'],
        [2021, 'Remake necesario', 'Remake que nadie pidió'],
        [2022, 'Personaje que me gustaría ser', 'Personaje que odiaría ser'],
        [2023, 'Famoso en internet', 'Famoso de verdad'],
        [2024, 'Peli demasiado corta', 'Peli demasiado larga'],
        [2025, 'Final que nadie entendió', 'Final obvio'],
        [2026, 'Giro predecible', 'Giro que te vuela la cabeza'],
        [2027, 'Disfraz fácil', 'Disfraz difícil'],
        [2028, 'Vale doblada', 'Solo en versión original'],
        [2029, 'El libro era mejor', 'La peli era mejor'],
        [2030, 'Referencia rebuscada', 'Referencia que pilla todo el mundo'],
        [2031, 'Superhéroe flojo', 'Superhéroe chetado'],
        [2032, 'Mundo de ficción para vivir', 'Mundo de ficción del que huir'],
        [2033, 'Pareja de ficción que no funciona', 'Pareja de ficción perfecta'],
        [2034, 'Banda de garaje', 'Banda de estadio'],
        [2035, 'Canción para llorar', 'Canción para bailar'],
        [2036, 'Videoclip olvidable', 'Videoclip histórico'],
        [2037, 'Juego de mesa aburrido', 'Juego de mesa adictivo'],
        [2038, 'Moda que debería volver', 'Moda que debería quedarse en el pasado'],
        [2039, 'App inútil', 'App imprescindible'],
        [2040, 'Tendencia tonta', 'Tendencia genial'],
        [2041, 'Intro que me salto', 'Intro que canto entera'],
        [2042, 'Actor de un solo papel', 'Actor camaleónico'],
        [2043, 'Peli de Navidad', 'No es peli de Navidad'],
        [2044, 'Escena de acción exagerada', 'Escena de acción realista'],
    ],

    people: [
        [3001, 'Madrugador', 'Noctámbulo'],
        [3002, 'Contesta al momento', 'Te deja en visto'],
        [3003, 'Llega antes de tiempo', 'Siempre llega tarde'],
        [3004, 'Habla bajito', 'Habla demasiado alto'],
        [3005, 'Lo planea todo', 'Vive improvisando'],
        [3006, 'Rencoroso', 'Olvida rápido'],
        [3007, 'Manirroto', 'Tacaño'],
        [3008, 'Audio cortito', 'Audio de cinco minutos'],
        [3009, 'Amigo para la fiesta', 'Amigo para una emergencia'],
        [3010, 'Chisme inofensivo', 'Chisme peligroso'],
        [3011, 'Cumplido sincero', 'Cumplido envenenado'],
        [3012, 'Pregunta normal', 'Pregunta indiscreta'],
        [3013, 'Consejo de oro', 'Consejo pésimo'],
        [3014, 'Hobby de jubilado', 'Hobby de adolescente'],
        [3015, 'Recuerdo bonito', 'Recuerdo bochornoso'],
        [3016, 'Pequeño desliz', 'Ridículo histórico'],
        [3017, 'Vecino ideal', 'Vecino del infierno'],
        [3018, 'Compañero de trabajo ideal', 'Compañero de trabajo insoportable'],
        [3019, 'Solo lo hago yo', 'Lo hace todo el mundo'],
        [3020, 'Pelea tonta', 'Pelea seria'],
        [3021, 'Mal mentiroso', 'Mentiroso profesional'],
        [3022, 'Nada competitivo', 'Demasiado competitivo'],
        [3023, 'Pide perdón por todo', 'Nunca pide perdón'],
        [3024, 'Hace la maleta la víspera', 'Hace la maleta un mes antes'],
        [3025, 'Aceptable en una primera cita', 'Inaceptable en una primera cita'],
        [3026, 'Fácil de regalar', 'Imposible de regalar'],
        [3027, 'Cabezota', 'Se deja llevar'],
        [3028, 'Acepta bien las críticas', 'No soporta una crítica'],
        [3029, 'Se ríe de todo', 'No se ríe de nada'],
        [3030, 'Educado en el cine', 'Vetado en el cine'],
        [3031, 'Se puede hacer en público', 'Solo en casa y a solas'],
        [3032, 'Motivo tonto para cortar', 'Motivo serio para cortar'],
        [3033, 'Amigo de la infancia', 'Amigo de copas'],
        [3034, 'Jefe soñado', 'Jefe de pesadilla'],
        [3035, 'Tranquilo al volante', 'Furioso al volante'],
        [3036, 'Vive en el pasado', 'Vive en el futuro'],
        [3037, 'Capricho justificable', 'Capricho injustificable'],
        [3038, 'De perros', 'De gatos'],
        [3039, 'Mochilero', 'Resort todo incluido'],
        [3040, 'Paciencia cero', 'Paciencia infinita'],
        [3041, 'Charla en el ascensor', 'Mira el móvil para no hablar'],
        [3042, 'Guarda secretos', 'Lo cuenta todo'],
        [3043, 'Opinión popular', 'Opinión polémica'],
        [3044, 'Demasiado responsable', 'Irresponsable'],
    ],

    spicy: [
        [4001, 'Coqueteo discreto', 'Coqueteo descarado'],
        [4002, 'Primer beso horrible', 'Primer beso de película'],
        [4003, 'Piropo malo', 'Piropo irresistible'],
        [4004, 'Se lo cuento a mi terapeuta', 'Me lo llevo a la tumba'],
        [4005, 'Gesto romántico', 'Gesto que da vergüenza ajena'],
        [4006, 'Nada sexy', 'Muy sexy'],
        [4007, 'Resaca leve', 'Resaca de otro planeta'],
        [4008, 'Mensaje inocente de madrugada', 'Mensaje peligroso de madrugada'],
        [4009, 'Volver con tu ex', 'Bloquear a tu ex'],
        [4010, 'Fantasía corriente', 'Fantasía atrevida'],
        [4011, 'Sitio clásico para un beso', 'Sitio inesperado para un beso'],
        [4012, 'Se lo puedo contar a mi madre', 'Mi madre nunca lo sabrá'],
        [4013, 'Foto de perfil formalita', 'Foto de perfil provocativa'],
        [4014, 'Perfil de citas fiable', 'Perfil de citas sospechoso'],
        [4015, 'Match al instante', 'Descartado sin piedad'],
        [4016, 'Copa para impresionar', 'Copa para olvidar'],
        [4017, 'Fiesta tranquila', 'Fiesta legendaria'],
        [4018, 'Pecadillo', 'Pecado capital'],
        [4019, 'Amor de verano', 'Amor para toda la vida'],
        [4020, 'Celos tiernos', 'Celos tóxicos'],
        [4021, 'Cotilleo aburrido', 'Cotilleo jugoso'],
        [4022, 'Secreto de amigos', 'Secreto de Estado'],
        [4023, 'Pregunta de primera cita', 'Pregunta de décima cita'],
        [4024, 'Atracción física', 'Atracción intelectual'],
        [4025, 'Encanto natural', 'Encanto ensayado'],
        [4026, 'Metedura de pata borracho perdonable', 'Metedura de pata borracho imperdonable'],
        [4027, 'Apto para el grupo familiar', 'Jamás en el grupo familiar'],
        [4028, 'Ropa de cita discreta', 'Ropa de cita provocativa'],
        [4029, 'Charla de pareja normal', 'Charla de pareja que nadie quiere oír'],
        [4030, 'Le quita un poco las ganas', 'Corta todo el rollo'],
        [4031, 'Mentira aceptable en una app de citas', 'Mentira imperdonable en una app de citas'],
        [4032, 'Noche para recordar', 'Noche para olvidar'],
        [4033, 'Cero química', 'Saltan chispas'],
        [4034, 'Declaración tierna', 'Declaración cursi'],
        [4035, 'Solo un rollo', 'Para casarse'],
        [4036, 'Manía en la cama tolerable', 'Manía en la cama inaceptable'],
        [4037, 'Inocente', 'Pícaro'],
        [4038, 'Indirecta sutil', 'Indirecta descarada'],
        [4039, 'Arrepentimiento inmediato', 'Arrepentimiento al día siguiente'],
        [4040, 'Vale la pena el ridículo', 'No vale la pena el ridículo'],
        [4041, 'Despedida de soltero tranquila', 'Despedida de soltero legendaria'],
        [4042, 'Santo', 'Pecador'],
        [4043, 'Beso de telenovela', 'Beso de tía'],
        [4044, 'Me gusta inocente', 'Me gusta con segundas intenciones'],
    ],
}
