import type { CardTextDeck } from '../types.ts'

/**
 * Baralho em português. Cada carta é [id, esquerda, direita]; os ids e os
 * pacotes são os mesmos em todos os idiomas (tests/cards.test.ts confere).
 */
export const ptBRCards: CardTextDeck = {
    // O baralho original de 142 cartas (opinião, comida, coisas, pessoas,
    // situações, natureza e abstratos).
    classic: [
        [1, 'Subestimado', 'Superestimado'],
        [2, 'Filme ruim', 'Filme bom'],
        [3, 'Música ruim', 'Música boa'],
        [4, 'Série ruim', 'Série boa'],
        [5, 'Livro chato', 'Livro bom'],
        [6, 'Brega', 'Chique'],
        [7, 'Cafona', 'Estiloso'],
        [8, 'Ultrapassado', 'Na moda'],
        [9, 'Nerd', 'Descolado'],
        [10, 'Clássico', 'Modinha'],
        [11, 'Esquecível', 'Inesquecível'],
        [12, 'Arte', 'Não é arte'],
        [13, 'Esporte', 'Não é esporte'],
        [14, 'Hobby', 'Profissão'],
        [15, 'Talento', 'Habilidade treinada'],
        [16, 'Guilty pleasure', 'Orgulho de gostar'],
        [17, 'Piada ruim', 'Piada boa'],
        [18, 'Sem graça', 'Engraçado'],
        [19, 'Cringe', 'Maneiro'],
        [20, 'Vilão', 'Herói'],
        [21, 'Personagem chato', 'Personagem amado'],
        [22, 'Mal interpretado', 'Bem interpretado'],
        [23, 'Final ruim', 'Final bom'],
        [24, 'Previsível', 'Surpreendente'],
        [25, 'Comida ruim', 'Comida boa'],
        [26, 'Gosto ruim', 'Gosto bom'],
        [27, 'Cheiro ruim', 'Cheiro bom'],
        [28, 'Pouco calórico', 'Muito calórico'],
        [29, 'Nada nutritivo', 'Super nutritivo'],
        [30, 'Café da manhã', 'Jantar'],
        [31, 'Lanche', 'Refeição'],
        [32, 'Doce', 'Salgado'],
        [33, 'Sem tempero', 'Muito temperado'],
        [34, 'Comida de criança', 'Comida de adulto'],
        [35, 'Se come com a mão', 'Se come com talher'],
        [36, 'Combina com ketchup', 'Não combina com ketchup'],
        [37, 'Sobremesa', 'Prato principal'],
        [38, 'Bebida de verão', 'Bebida de inverno'],
        [39, 'Comida caseira', 'Comida de restaurante'],
        [40, 'Fruta ruim', 'Fruta boa'],
        [41, 'Pizza aceitável', 'Pizza inaceitável'],
        [42, 'Inútil', 'Essencial'],
        [43, 'Barato', 'Caro'],
        [44, 'Frágil', 'Resistente'],
        [45, 'Descartável', 'Para a vida toda'],
        [46, 'Fácil de achar', 'Difícil de achar'],
        [47, 'Comum', 'Raro'],
        [48, 'Velho', 'Novo'],
        [49, 'Antigo', 'Moderno'],
        [50, 'Pequeno', 'Grande'],
        [51, 'Leve', 'Pesado'],
        [52, 'Macio', 'Duro'],
        [53, 'Redondo', 'Pontudo'],
        [54, 'Liso', 'Áspero'],
        [55, 'Seco', 'Molhado'],
        [56, 'Quente', 'Frio'],
        [57, 'Silencioso', 'Barulhento'],
        [58, 'Feio', 'Bonito'],
        [59, 'Cabe no bolso', 'Precisa de caminhão'],
        [60, 'Tecnologia inútil', 'Tecnologia revolucionária'],
        [61, 'Brinquedo', 'Ferramenta'],
        [62, 'Decoração', 'Utilidade'],
        [63, 'Presente ruim', 'Presente bom'],
        [64, 'Coisa de criança', 'Coisa de adulto'],
        [65, 'Coisa de casa', 'Coisa de escritório'],
        [66, 'Introvertido', 'Extrovertido'],
        [67, 'Tímido', 'Ousado'],
        [68, 'Preguiçoso', 'Trabalhador'],
        [69, 'Sincero demais', 'Educado demais'],
        [70, 'Mentira inocente', 'Mentira grave'],
        [71, 'Hábito ruim', 'Hábito bom'],
        [72, 'Mania aceitável', 'Mania insuportável'],
        [73, 'Superpoder inútil', 'Superpoder incrível'],
        [74, 'Profissão chata', 'Profissão legal'],
        [75, 'Profissão perigosa', 'Profissão segura'],
        [76, 'Mal pago', 'Bem pago'],
        [77, 'Nome comum', 'Nome raro'],
        [78, 'Nome de cachorro', 'Nome de gato'],
        [79, 'Desculpa esfarrapada', 'Desculpa válida'],
        [80, 'Otimista', 'Pessimista'],
        [81, 'Realista', 'Sonhador'],
        [82, 'Falta de educação', 'Boa educação'],
        [83, 'Coisa de gente velha', 'Coisa de gente jovem'],
        [84, 'Conversa de bar', 'Conversa de trabalho'],
        [85, 'Primeiro encontro ruim', 'Primeiro encontro bom'],
        [86, 'Red flag', 'Green flag'],
        [87, 'Tarefa fácil', 'Tarefa difícil'],
        [88, 'Chato de fazer', 'Divertido de fazer'],
        [89, 'Relaxante', 'Estressante'],
        [90, 'Seguro', 'Perigoso'],
        [91, 'Cansativo', 'Revigorante'],
        [92, 'Rápido', 'Demorado'],
        [93, 'Dá para fazer dormindo', 'Exige concentração total'],
        [94, 'Atividade de dia', 'Atividade de noite'],
        [95, 'Programa de verão', 'Programa de inverno'],
        [96, 'Programa de família', 'Programa de amigos'],
        [97, 'Viagem ruim', 'Viagem dos sonhos'],
        [98, 'Lugar para visitar', 'Lugar para morar'],
        [99, 'Cidade pequena', 'Cidade grande'],
        [100, 'Formal', 'Casual'],
        [101, 'Tradicional', 'Inovador'],
        [102, 'Vale a pena', 'Não vale a pena'],
        [103, 'Perda de tempo', 'Bom uso do tempo'],
        [104, 'Dá azar', 'Dá sorte'],
        [105, 'Coisa de segunda-feira', 'Coisa de sábado'],
        [106, 'Para fazer sozinho', 'Para fazer em grupo'],
        [107, 'Animal fofo', 'Animal assustador'],
        [108, 'Animal inofensivo', 'Animal perigoso'],
        [109, 'Animal burro', 'Animal inteligente'],
        [110, 'Vive pouco', 'Vive muito'],
        [111, 'Lento', 'Rápido'],
        [112, 'Fraco', 'Forte'],
        [113, 'Pequeno demais para ver', 'Grande demais para imaginar'],
        [114, 'Natural', 'Artificial'],
        [115, 'Limpo', 'Sujo'],
        [116, 'Saudável', 'Faz mal'],
        [117, 'Ciência', 'Pseudociência'],
        [118, 'Fato', 'Opinião'],
        [119, 'Cedo', 'Tarde'],
        [120, 'Passado', 'Futuro'],
        [121, 'Problema pequeno', 'Problema enorme'],
        [122, 'Probabilidade zero', 'Certeza absoluta'],
        [123, 'Bom', 'Mau'],
        [124, 'Simples', 'Complexo'],
        [125, 'Normal', 'Estranho'],
        [126, 'Fácil', 'Difícil'],
        [127, 'Divertido', 'Tedioso'],
        [128, 'Famoso', 'Desconhecido'],
        [129, 'Honesto', 'Desonesto'],
        [130, 'Generoso', 'Egoísta'],
        [131, 'Corajoso', 'Covarde'],
        [132, 'Importante', 'Irrelevante'],
        [133, 'Frescura', 'Necessidade'],
        [134, 'Overrated', 'Underrated'],
        [135, 'Infantil', 'Maduro'],
        [136, 'Romântico', 'Nada romântico'],
        [137, 'Pecado', 'Virtude'],
        [138, 'Caótico', 'Organizado'],
        [139, 'Medo bobo', 'Medo justificado'],
        [140, 'Invenção boa', 'Invenção ruim'],
        [141, 'Começo de história', 'Fim de história'],
        [142, 'Coisa que todo mundo tem', 'Coisa que ninguém tem'],
    ],

    food: [
        [1001, 'Comida de boteco', 'Comida de restaurante chique'],
        [1002, 'Café fraco', 'Café forte'],
        [1003, 'Comida leve', 'Comida que pesa'],
        [1004, 'Combinação estranha', 'Combinação perfeita'],
        [1005, 'Ingrediente que estraga tudo', 'Ingrediente que salva tudo'],
        [1006, 'Comida de festa infantil', 'Comida de casamento'],
        [1007, 'Não arde nada', 'Arde muito'],
        [1008, 'Comida de hospital', 'Comida de vó'],
        [1009, 'Fácil de cozinhar', 'Difícil de cozinhar'],
        [1010, 'Fica pronto em 5 minutos', 'Leva o dia inteiro'],
        [1011, 'Barato no mercado', 'Caro no mercado'],
        [1012, 'Gosto adquirido', 'Todo mundo gosta de cara'],
        [1013, 'Comida de madrugada', 'Almoço de domingo'],
        [1014, 'Lanche de cinema ruim', 'Lanche de cinema perfeito'],
        [1015, 'Mole', 'Crocante'],
        [1016, 'Sem cheiro', 'Cheiro forte'],
        [1017, 'Saudável de verdade', 'Finge que é saudável'],
        [1018, 'Comida fitness', 'Comida gordurosa'],
        [1019, 'Prato do dia a dia', 'Prato de ocasião especial'],
        [1020, 'Dá para dividir', 'Não divido com ninguém'],
        [1021, 'Peço no delivery', 'Faço em casa'],
        [1022, 'Tempero indispensável', 'Tempero dispensável'],
        [1023, 'Sobremesa leve', 'Sobremesa enjoativa'],
        [1024, 'Mata a sede', 'Dá mais sede'],
        [1025, 'Comida feia', 'Comida instagramável'],
        [1026, 'Comida de criança enjoada', 'Comida de quem come de tudo'],
        [1027, 'Comida de avião', 'Comida de chef'],
        [1028, 'Pode comer frio', 'Só presta quente'],
        [1029, 'Vai bem com arroz', 'Nunca com arroz'],
        [1030, 'Comida de praia', 'Comida de serra'],
        [1031, 'Come sem se sujar', 'Suja a cara toda'],
        [1032, 'Bebida doce demais', 'Bebida amarga demais'],
        [1033, 'Comida de rua', 'Comida de mesa posta'],
        [1034, 'Ingrediente básico', 'Ingrediente gourmet'],
        [1035, 'Combina com tudo', 'Não combina com nada'],
        [1036, 'Dura dias na geladeira', 'Estraga no mesmo dia'],
        [1037, 'Prato típico subestimado', 'Prato típico superestimado'],
        [1038, 'Prato para impressionar visita', 'Prato para comer sozinho no sofá'],
        [1039, 'Bebida de festa', 'Bebida de ressaca'],
        [1040, 'Precisa de receita', 'Faz no olho'],
        [1041, 'Sabor de infância', 'Sabor que acabei de descobrir'],
        [1042, 'Cozinha de solteiro', 'Cozinha de MasterChef'],
        [1043, 'Fruta de feira', 'Fruta exótica'],
        [1044, 'Café da manhã de hotel ruim', 'Café da manhã de hotel dos sonhos'],
    ],

    pop: [
        [2001, 'Filme de Sessão da Tarde', 'Filme de Oscar'],
        [2002, 'Personagem esquecível', 'Personagem icônico'],
        [2003, 'Música para relaxar', 'Música para pular'],
        [2004, 'Karaokê fácil', 'Karaokê impossível'],
        [2005, 'Continuação desnecessária', 'Continuação melhor que o original'],
        [2006, 'Spoiler leve', 'Spoiler imperdoável'],
        [2007, 'Programa trash', 'Programa de qualidade'],
        [2008, 'Meme morto', 'Meme eterno'],
        [2009, 'Celebridade discreta', 'Celebridade escandalosa'],
        [2010, 'Vilão incompreendido', 'Vilão sem perdão'],
        [2011, 'Jogo para relaxar', 'Jogo que dá raiva'],
        [2012, 'Jogo casual', 'Jogo hardcore'],
        [2013, 'Série para maratonar', 'Série para ver aos poucos'],
        [2014, 'Filme para ver sozinho', 'Filme para ver com a família'],
        [2015, 'Terror que dá medo', 'Terror que dá risada'],
        [2016, 'Trilha sonora esquecível', 'Trilha sonora icônica'],
        [2017, 'Fama merecida', 'Fama sem explicação'],
        [2018, 'Desenho para crianças', 'Desenho para adultos'],
        [2019, 'Música chiclete', 'Música que ninguém lembra'],
        [2020, 'Hit de um verão', 'Música eterna'],
        [2021, 'Remake necessário', 'Remake desnecessário'],
        [2022, 'Personagem que eu queria ser', 'Personagem que eu odiaria ser'],
        [2023, 'Famoso na internet', 'Famoso de verdade'],
        [2024, 'Filme curto demais', 'Filme longo demais'],
        [2025, 'Final que ninguém entendeu', 'Final óbvio'],
        [2026, 'Reviravolta previsível', 'Reviravolta chocante'],
        [2027, 'Fantasia de Carnaval fácil', 'Fantasia de Carnaval difícil'],
        [2028, 'Pode ver dublado', 'Só presta legendado'],
        [2029, 'Livro melhor que o filme', 'Filme melhor que o livro'],
        [2030, 'Referência obscura', 'Referência que todo mundo pega'],
        [2031, 'Super-herói fraco', 'Super-herói apelão'],
        [2032, 'Universo de ficção para morar', 'Universo de ficção para fugir'],
        [2033, 'Casal fictício que não funciona', 'Casal fictício perfeito'],
        [2034, 'Banda de garagem', 'Banda de estádio'],
        [2035, 'Música para chorar', 'Música para dançar'],
        [2036, 'Clipe esquecível', 'Clipe histórico'],
        [2037, 'Jogo de tabuleiro chato', 'Jogo de tabuleiro viciante'],
        [2038, 'Moda que deveria voltar', 'Moda que deveria ficar no passado'],
        [2039, 'Aplicativo inútil', 'Aplicativo indispensável'],
        [2040, 'Trend boba', 'Trend genial'],
        [2041, 'Abertura que eu pulo', 'Abertura que eu canto junto'],
        [2042, 'Ator de um papel só', 'Ator camaleão'],
        [2043, 'Filme de Natal', 'Não é filme de Natal'],
        [2044, 'Cena de ação exagerada', 'Cena de ação realista'],
    ],

    people: [
        [3001, 'Pessoa da manhã', 'Pessoa da noite'],
        [3002, 'Responde na hora', 'Visualiza e não responde'],
        [3003, 'Chega adiantado', 'Sempre atrasado'],
        [3004, 'Fala baixinho', 'Fala alto demais'],
        [3005, 'Planeja tudo', 'Vive no improviso'],
        [3006, 'Guarda rancor', 'Esquece rápido'],
        [3007, 'Mão aberta', 'Pão-duro'],
        [3008, 'Áudio curtinho', 'Áudio de cinco minutos'],
        [3009, 'Amigo para a festa', 'Amigo para a emergência'],
        [3010, 'Fofoca inofensiva', 'Fofoca perigosa'],
        [3011, 'Elogio sincero', 'Elogio falso'],
        [3012, 'Pergunta normal', 'Pergunta indiscreta'],
        [3013, 'Conselho de ouro', 'Conselho péssimo'],
        [3014, 'Hobby de aposentado', 'Hobby de adolescente'],
        [3015, 'Lembrança boa', 'Lembrança constrangedora'],
        [3016, 'Gafe pequena', 'Mico histórico'],
        [3017, 'Vizinho ideal', 'Vizinho do inferno'],
        [3018, 'Colega de trabalho ideal', 'Colega de trabalho insuportável'],
        [3019, 'Coisa que só eu faço', 'Coisa que todo mundo faz'],
        [3020, 'Briga boba', 'Briga séria'],
        [3021, 'Mentiroso ruim', 'Mentiroso profissional'],
        [3022, 'Nada competitivo', 'Competitivo demais'],
        [3023, 'Pede desculpa por tudo', 'Nunca pede desculpa'],
        [3024, 'Faz a mala na véspera', 'Faz a mala um mês antes'],
        [3025, 'Aceitável no primeiro encontro', 'Inaceitável no primeiro encontro'],
        [3026, 'Fácil de presentear', 'Impossível de presentear'],
        [3027, 'Teimoso', 'Vai na onda de todo mundo'],
        [3028, 'Lida bem com crítica', 'Não aceita crítica'],
        [3029, 'Ri de tudo', 'Não ri de nada'],
        [3030, 'Educado no cinema', 'Proibido no cinema'],
        [3031, 'Dá para fazer em público', 'Só se faz sozinho em casa'],
        [3032, 'Motivo bobo para terminar', 'Motivo sério para terminar'],
        [3033, 'Amizade de infância', 'Amizade de bar'],
        [3034, 'Chefe dos sonhos', 'Chefe pesadelo'],
        [3035, 'Calmo no trânsito', 'Estressado no trânsito'],
        [3036, 'Vive no passado', 'Vive no futuro'],
        [3037, 'Gasto justificável', 'Gasto injustificável'],
        [3038, 'Pessoa de cachorro', 'Pessoa de gato'],
        [3039, 'Viaja de mochila', 'Viaja para resort'],
        [3040, 'Paciência zero', 'Paciência infinita'],
        [3041, 'Puxa assunto no elevador', 'Finge que está no celular'],
        [3042, 'Sabe guardar segredo', 'Conta tudo para todo mundo'],
        [3043, 'Opinião popular', 'Opinião polêmica'],
        [3044, 'Responsável demais', 'Irresponsável'],
    ],

    // Adulto e picante, mas sem conteúdo explícito ou ofensivo.
    spicy: [
        [4001, 'Paquera discreta', 'Paquera escancarada'],
        [4002, 'Primeiro beijo péssimo', 'Primeiro beijo de cinema'],
        [4003, 'Cantada ruim', 'Cantada irresistível'],
        [4004, 'Conto para a terapeuta', 'Levo para o túmulo'],
        [4005, 'Gesto romântico', 'Gesto constrangedor'],
        [4006, 'Nada sexy', 'Muito sexy'],
        [4007, 'Ressaca leve', 'Ressaca de outro mundo'],
        [4008, 'Mensagem de madrugada inocente', 'Mensagem de madrugada perigosa'],
        [4009, 'Volta com o ex', 'Bloqueia o ex'],
        [4010, 'Fantasia comum', 'Fantasia ousada'],
        [4011, 'Lugar clássico para um beijo', 'Lugar inusitado para um beijo'],
        [4012, 'Posso contar para a minha mãe', 'Nunca contar para a minha mãe'],
        [4013, 'Foto de perfil comportada', 'Foto de perfil ousada'],
        [4014, 'Perfil de app de namoro confiável', 'Perfil de app de namoro suspeito'],
        [4015, 'Dá match na hora', 'Arrasta para o lado sem dó'],
        [4016, 'Bebida para impressionar', 'Bebida para esquecer'],
        [4017, 'Festa tranquila', 'Festa que vira lenda'],
        [4018, 'Pecadinho', 'Pecado capital'],
        [4019, 'Paixão de verão', 'Amor para a vida toda'],
        [4020, 'Ciúme fofo', 'Ciúme tóxico'],
        [4021, 'Fofoca sem graça', 'Fofoca picante'],
        [4022, 'Segredo de amigo', 'Segredo de Estado'],
        [4023, 'Pergunta de primeiro encontro', 'Pergunta de décimo encontro'],
        [4024, 'Atração física', 'Atração intelectual'],
        [4025, 'Charme natural', 'Charme ensaiado'],
        [4026, 'Vacilo de bêbado perdoável', 'Vacilo de bêbado imperdoável'],
        [4027, 'Pode mandar no grupo da família', 'Jamais no grupo da família'],
        [4028, 'Roupa de encontro discreta', 'Roupa de encontro provocante'],
        [4029, 'Conversa de casal normal', 'Conversa de casal que ninguém quer ouvir'],
        [4030, 'Desanima um pouco', 'Brochante total'],
        [4031, 'Mentira de app de namoro aceitável', 'Mentira de app de namoro imperdoável'],
        [4032, 'Noitada para lembrar', 'Noitada para esquecer'],
        [4033, 'Clima nenhum', 'Clima no ar'],
        [4034, 'Declaração fofa', 'Declaração cafona'],
        [4035, 'Só um casinho', 'Para casar'],
        [4036, 'Mania na cama tolerável', 'Mania na cama inaceitável'],
        [4037, 'Inocente', 'Malicioso'],
        [4038, 'Indireta sutil', 'Indireta escancarada'],
        [4039, 'Arrependimento imediato', 'Arrependimento no dia seguinte'],
        [4040, 'Vale o vexame', 'Não vale o vexame'],
        [4041, 'Despedida de solteiro tranquila', 'Despedida de solteiro lendária'],
        [4042, 'Santo', 'Safado'],
        [4043, 'Beijo de novela', 'Beijo de tia'],
        [4044, 'Curtida inocente', 'Curtida com segundas intenções'],
    ],
}
