import type { SpectrumCard } from './types.ts'

/**
 * Spectrum cards, in the spirit of the physical SINTONIA / Wavelength deck.
 * The best cards are the ones where people disagree: a mix of objective
 * scales (quente/frio) and opinion scales (subestimado/superestimado).
 */
const RAW_CARDS: Array<[string, string]> = [
    // Opinião e cultura
    ['Subestimado', 'Superestimado'],
    ['Filme ruim', 'Filme bom'],
    ['Música ruim', 'Música boa'],
    ['Série ruim', 'Série boa'],
    ['Livro chato', 'Livro bom'],
    ['Brega', 'Chique'],
    ['Cafona', 'Estiloso'],
    ['Ultrapassado', 'Na moda'],
    ['Nerd', 'Descolado'],
    ['Clássico', 'Modinha'],
    ['Esquecível', 'Inesquecível'],
    ['Arte', 'Não é arte'],
    ['Esporte', 'Não é esporte'],
    ['Hobby', 'Profissão'],
    ['Talento', 'Habilidade treinada'],
    ['Guilty pleasure', 'Orgulho de gostar'],
    ['Piada ruim', 'Piada boa'],
    ['Sem graça', 'Engraçado'],
    ['Cringe', 'Maneiro'],
    ['Vilão', 'Herói'],
    ['Personagem chato', 'Personagem amado'],
    ['Mal interpretado', 'Bem interpretado'],
    ['Final ruim', 'Final bom'],
    ['Previsível', 'Surpreendente'],

    // Comida e bebida
    ['Comida ruim', 'Comida boa'],
    ['Gosto ruim', 'Gosto bom'],
    ['Cheiro ruim', 'Cheiro bom'],
    ['Pouco calórico', 'Muito calórico'],
    ['Nada nutritivo', 'Super nutritivo'],
    ['Café da manhã', 'Jantar'],
    ['Lanche', 'Refeição'],
    ['Doce', 'Salgado'],
    ['Sem tempero', 'Muito temperado'],
    ['Comida de criança', 'Comida de adulto'],
    ['Se come com a mão', 'Se come com talher'],
    ['Combina com ketchup', 'Não combina com ketchup'],
    ['Sobremesa', 'Prato principal'],
    ['Bebida de verão', 'Bebida de inverno'],
    ['Comida caseira', 'Comida de restaurante'],
    ['Fruta ruim', 'Fruta boa'],
    ['Pizza aceitável', 'Pizza inaceitável'],

    // Coisas e objetos
    ['Inútil', 'Essencial'],
    ['Barato', 'Caro'],
    ['Frágil', 'Resistente'],
    ['Descartável', 'Para a vida toda'],
    ['Fácil de achar', 'Difícil de achar'],
    ['Comum', 'Raro'],
    ['Velho', 'Novo'],
    ['Antigo', 'Moderno'],
    ['Pequeno', 'Grande'],
    ['Leve', 'Pesado'],
    ['Macio', 'Duro'],
    ['Redondo', 'Pontudo'],
    ['Liso', 'Áspero'],
    ['Seco', 'Molhado'],
    ['Quente', 'Frio'],
    ['Silencioso', 'Barulhento'],
    ['Feio', 'Bonito'],
    ['Cabe no bolso', 'Precisa de caminhão'],
    ['Tecnologia inútil', 'Tecnologia revolucionária'],
    ['Brinquedo', 'Ferramenta'],
    ['Decoração', 'Utilidade'],
    ['Presente ruim', 'Presente bom'],
    ['Coisa de criança', 'Coisa de adulto'],
    ['Coisa de casa', 'Coisa de escritório'],

    // Pessoas e comportamento
    ['Introvertido', 'Extrovertido'],
    ['Tímido', 'Ousado'],
    ['Preguiçoso', 'Trabalhador'],
    ['Sincero demais', 'Educado demais'],
    ['Mentira inocente', 'Mentira grave'],
    ['Hábito ruim', 'Hábito bom'],
    ['Mania aceitável', 'Mania insuportável'],
    ['Superpoder inútil', 'Superpoder incrível'],
    ['Profissão chata', 'Profissão legal'],
    ['Profissão perigosa', 'Profissão segura'],
    ['Mal pago', 'Bem pago'],
    ['Nome comum', 'Nome raro'],
    ['Nome de cachorro', 'Nome de gato'],
    ['Desculpa esfarrapada', 'Desculpa válida'],
    ['Otimista', 'Pessimista'],
    ['Realista', 'Sonhador'],
    ['Falta de educação', 'Boa educação'],
    ['Coisa de gente velha', 'Coisa de gente jovem'],
    ['Conversa de bar', 'Conversa de trabalho'],
    ['Primeiro encontro ruim', 'Primeiro encontro bom'],
    ['Red flag', 'Green flag'],

    // Atividades e situações
    ['Tarefa fácil', 'Tarefa difícil'],
    ['Chato de fazer', 'Divertido de fazer'],
    ['Relaxante', 'Estressante'],
    ['Seguro', 'Perigoso'],
    ['Cansativo', 'Revigorante'],
    ['Rápido', 'Demorado'],
    ['Dá para fazer dormindo', 'Exige concentração total'],
    ['Atividade de dia', 'Atividade de noite'],
    ['Programa de verão', 'Programa de inverno'],
    ['Programa de família', 'Programa de amigos'],
    ['Viagem ruim', 'Viagem dos sonhos'],
    ['Lugar para visitar', 'Lugar para morar'],
    ['Cidade pequena', 'Cidade grande'],
    ['Formal', 'Casual'],
    ['Tradicional', 'Inovador'],
    ['Vale a pena', 'Não vale a pena'],
    ['Perda de tempo', 'Bom uso do tempo'],
    ['Dá azar', 'Dá sorte'],
    ['Coisa de segunda-feira', 'Coisa de sábado'],
    ['Para fazer sozinho', 'Para fazer em grupo'],

    // Natureza e ciência
    ['Animal fofo', 'Animal assustador'],
    ['Animal inofensivo', 'Animal perigoso'],
    ['Animal burro', 'Animal inteligente'],
    ['Vive pouco', 'Vive muito'],
    ['Lento', 'Rápido'],
    ['Fraco', 'Forte'],
    ['Pequeno demais para ver', 'Grande demais para imaginar'],
    ['Natural', 'Artificial'],
    ['Limpo', 'Sujo'],
    ['Saudável', 'Faz mal'],
    ['Ciência', 'Pseudociência'],
    ['Fato', 'Opinião'],
    ['Cedo', 'Tarde'],
    ['Passado', 'Futuro'],
    ['Problema pequeno', 'Problema enorme'],
    ['Probabilidade zero', 'Certeza absoluta'],

    // Abstratos
    ['Bom', 'Mau'],
    ['Simples', 'Complexo'],
    ['Normal', 'Estranho'],
    ['Fácil', 'Difícil'],
    ['Divertido', 'Tedioso'],
    ['Famoso', 'Desconhecido'],
    ['Honesto', 'Desonesto'],
    ['Generoso', 'Egoísta'],
    ['Corajoso', 'Covarde'],
    ['Importante', 'Irrelevante'],
    ['Frescura', 'Necessidade'],
    ['Overrated', 'Underrated'],
    ['Infantil', 'Maduro'],
    ['Romântico', 'Nada romântico'],
    ['Pecado', 'Virtude'],
    ['Caótico', 'Organizado'],
    ['Medo bobo', 'Medo justificado'],
    ['Invenção boa', 'Invenção ruim'],
    ['Começo de história', 'Fim de história'],
    ['Coisa que todo mundo tem', 'Coisa que ninguém tem'],
]

export const spectrumCards: SpectrumCard[] = RAW_CARDS.map(([leftConcept, rightConcept], i) => ({
    id: i + 1,
    leftConcept,
    rightConcept,
}))

export function getCardById(id: number): SpectrumCard | undefined {
    return spectrumCards.find(c => c.id === id)
}
